#!/usr/bin/env bash
#
# scripts/rollback.sh — snapshot / restore the installed substrate-guard tree
# (audit 2026-07-17 item #17: rollback automation).
#
# deploy.sh overwrites $INSTALL_DIR in place with no revert path. This script
# adds one: `backup` snapshots the currently-installed code BEFORE an overwrite,
# `restore` puts the last (or a named) snapshot back, `list` shows what exists.
#
# All paths are env-overridable so the backup/restore round-trip is unit-testable
# without touching /opt:
#   INSTALL_DIR   (default /opt/substrate-guard)
#   BACKUP_ROOT   (default $INSTALL_DIR/.backups)
#   KEEP          (default 3 — number of snapshots retained by `backup`)
#
# Usage:
#   scripts/rollback.sh backup            # snapshot current install, prune to KEEP
#   scripts/rollback.sh list              # list snapshots (newest first)
#   scripts/rollback.sh restore [<name>]  # restore newest (or named) snapshot
#
# Exit codes: 0 ok · 1 usage · 2 nothing to back up / no snapshot to restore
set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-/opt/substrate-guard}"
BACKUP_ROOT="${BACKUP_ROOT:-$INSTALL_DIR/.backups}"
KEEP="${KEEP:-3}"

# The code subtrees a deploy overwrites (config is regenerated by deploy.sh, so
# it is intentionally NOT snapshotted).
SUBTREES=(substrate_guard scripts)

log()  { echo "[rollback] $*"; }
err()  { echo "[rollback] ERROR: $*" >&2; }

_snapshots_newest_first() {
    # directory names under BACKUP_ROOT, lexically-reverse == newest first
    # (timestamps are %Y%m%d_%H%M%S so lexical order == chronological order)
    [ -d "$BACKUP_ROOT" ] || return 0
    find "$BACKUP_ROOT" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' 2>/dev/null \
        | sort -r
}

cmd_backup() {
    if [ ! -d "$INSTALL_DIR/substrate_guard" ]; then
        err "no installed tree at $INSTALL_DIR/substrate_guard — nothing to back up"
        return 2
    fi
    # Timestamp is passed in (tests inject STAMP for determinism); default = now.
    local ts="${STAMP:-$(date +%Y%m%d_%H%M%S)}"
    local dest="$BACKUP_ROOT/$ts"
    mkdir -p "$dest"
    for sub in "${SUBTREES[@]}"; do
        if [ -e "$INSTALL_DIR/$sub" ]; then
            cp -r "$INSTALL_DIR/$sub" "$dest/"
        fi
    done
    # Record the version if the installed package exposes one (best-effort).
    if [ -f "$INSTALL_DIR/substrate_guard/__init__.py" ]; then
        grep -E '^__version__' "$INSTALL_DIR/substrate_guard/__init__.py" \
            > "$dest/.version" 2>/dev/null || true
    fi
    log "snapshot saved: $dest"

    # Prune to the newest KEEP snapshots.
    local i=0
    while IFS= read -r name; do
        i=$((i + 1))
        if [ "$i" -gt "$KEEP" ]; then
            rm -rf "${BACKUP_ROOT:?}/$name"
            log "pruned old snapshot: $name"
        fi
    done < <(_snapshots_newest_first)
}

cmd_list() {
    local any=0
    while IFS= read -r name; do
        any=1
        local ver=""
        [ -f "$BACKUP_ROOT/$name/.version" ] && ver="$(cat "$BACKUP_ROOT/$name/.version")"
        echo "$name  $ver"
    done < <(_snapshots_newest_first)
    [ "$any" = 1 ] || log "no snapshots under $BACKUP_ROOT"
}

cmd_restore() {
    local want="${1:-}"
    local name
    if [ -n "$want" ]; then
        if [ ! -d "$BACKUP_ROOT/$want" ]; then
            err "snapshot not found: $want"
            return 2
        fi
        name="$want"
    else
        name="$(_snapshots_newest_first | head -1)"
        if [ -z "$name" ]; then
            err "no snapshot to restore under $BACKUP_ROOT"
            return 2
        fi
    fi
    for sub in "${SUBTREES[@]}"; do
        if [ -e "$BACKUP_ROOT/$name/$sub" ]; then
            rm -rf "${INSTALL_DIR:?}/$sub"
            cp -r "$BACKUP_ROOT/$name/$sub" "$INSTALL_DIR/"
        fi
    done
    log "restored snapshot $name -> $INSTALL_DIR"
}

case "${1:-}" in
    backup)  cmd_backup ;;
    list)    cmd_list ;;
    restore) cmd_restore "${2:-}" ;;
    *)
        err "usage: $0 {backup|list|restore [<name>]}"
        exit 1
        ;;
esac
